"""Scientific settings of the April 2026 analysis policy, without site paths.

Profile presets are applied before explicitly supplied YAML/CLI values. Declared
but unused legacy toggles are retained for provenance, not silently implemented.
"""

UPDATED = {
    'EVAL_NBD': '1e-5', 'MIN_NBD_ALI_LEN': 180,
    'EVAL_NBD_RELAXED': '1e-3', 'MIN_NBD_ALI_LEN_RELAXED': 120,
    'PFAM_NBD_SCAN': 1, 'DISCOVERY_MODE': 'BALANCED',
    'INCLUDE_DESC_KEYWORDS_IN_UNION': 0, 'DESC_KEYWORD_REQUIRE_STRUCTURAL_HINT': 1,
    'DESC_KEYWORD_STRUCTURAL_HINT_MODE': 'ANY',
    'DESC_KEYWORD_STRUCTURAL_HINT_SOURCES': 'RELAXED_NBD,PFAM_NBD,PFAM_ENRICHED',
    'DESC_PRIORITY_KEYWORDS_REGEX': r'NACHT|NB-ARC|STAND|NOD-like|NOD-like receptor|NLR|P-loop NTPase|AAA\+|HET|het-e|incompatibility|vegetative incompatibility|HeLo|HELL|Goodbye|gasdermin|MLKL|necrosis|cell death|amyloid|prion|amyloid signaling|HRAM|PP-motif|PUASM|FASS|ASM|WD40|WD-repeat|ANK|ankyrin|TPR|tetratricopeptide|HEAT|kelch|SPRY|B30\.2|zinc finger|C2H2|ZZ-type|protein kinase|PKinase',
    'UNION_INTERSECT_WITH_PROTEOME_IDS': 1, 'USE_PFAM_ENRICHMENT_FOR_UNION': 1,
    'PFAM_ENRICH_MIN_FG_COUNT': 2, 'PFAM_ENRICH_MIN_LOG2FC': 1.0, 'PFAM_ENRICH_TOP_N': 50,
    'NBD_MODE': 'strict', 'PFAM_ENRICH_BG': 'candidates',
    'NBD_CONF_EV_HIGH': '1e-6', 'NBD_CONF_COV_HIGH': 0.45,
    'NBD_CONF_EV_MED': '1e-3', 'NBD_CONF_COV_MED': 0.25,
    'ASM_ENABLE': 1, 'ASM_WINDOW_NTERM_AA': 200, 'ASM_WINDOW_NBD_FLANK_AA': 100,
    'ASM_MAX_EVALUE': '1e-3', 'ASM_MIN_BITSCORE': 20, 'ASM_MIN_ALI_LEN': 12,
    'ASM_ALLOW_MULTIHIT': 1, 'ASM_LOW_COMPLEXITY_MASK': 1, 'ASM_COUNTS_AS_SENSOR': 0,
    'ENABLE_REPEATLIKE_SENSOR': 1,
    'REPEATLIKE_GROUPS_CSV': 'WD40,ANK,TPR,HEAT,KELCH,COILED_COIL,LOW_COMPLEXITY,DUF,RICH_REGION',
    'TIER_REPEATLIKE_UNKNOWN_SENSOR': 'TIER_2D_PROBABLE_UNKNOWN_SENSOR_REPEATLIKE',
    'NLR_PROFILE': 'ILLUMINA', 'HARD_END_BP': 10000, 'SUBTELO_BP': 0,
    'VERY_SHORT_PROTEIN_AA': 333, 'SHORT_PROTEIN_AA': 500,
    'HIC_IDENTITY_THRESHOLD': 85, 'REPEAT_COLLAPSE_SCORE_BONUS': 20,
    'SKIP_RESCUE_FOR_TIER1A': 1, 'INCLUDE_TIER3_IN_RESCUE': 0,
    'REQUIRE_NBD_OK_IN_RESCUE_FASTA': 0, 'RESCUE_FILTER_LOW_NBD': 0,
    'MINIPROT_EXTRA': '', 'EXON_MAX_INTRON_RETRY': 0,
    'ENABLE_FUSION': 1, 'MAX_FUSION_GAP_ILLUMINA': 50000, 'MAX_FUSION_GAP_HIFI': 20000,
    'FUSION_GAP_BOOST_HARD_END': 100000, 'FUSION_GAP_BOOST_REPEAT': 50000,
    'FUSION_MIN_NBD_CONF': 'MEDIUM', 'FUSION_MAX_OVERLAP': 200, 'FUSION_MAX_MEMBERS': 3,
    'FUSION_EXCLUDE_FLAGS': 'LRR,FP_DOMAIN_OVERLAPS_NBD',
    'FUSION_NAMESPACE_MODE': 'TRACK', 'FUSION_PRIORITY_PREFIX': 'PRIORITY',
    'FUSION_COMPREHENSIVE_PREFIX': 'COMPREHENSIVE', 'FUSION_ID_PAD_WIDTH': 6,
    'REPORT_PLOT_BACKEND': 'matplotlib', 'REPORT_PLOTS': 1, 'REPORT_INTEGRATION': 1, 'REPORT_TAGGED_GFF3': 1,
    'REPORT_TAGGED_EGGNOG': 1, 'REPORT_PROTEINS': 1,
}

GROUPS = {
    'discovery': 'EVAL_NBD_RELAXED MIN_NBD_ALI_LEN_RELAXED PFAM_NBD_SCAN DISCOVERY_MODE INCLUDE_DESC_KEYWORDS_IN_UNION DESC_KEYWORD_REQUIRE_STRUCTURAL_HINT DESC_KEYWORD_STRUCTURAL_HINT_MODE DESC_KEYWORD_STRUCTURAL_HINT_SOURCES DESC_PRIORITY_KEYWORDS_REGEX UNION_INTERSECT_WITH_PROTEOME_IDS USE_PFAM_ENRICHMENT_FOR_UNION PFAM_ENRICH_MIN_FG_COUNT PFAM_ENRICH_MIN_LOG2FC PFAM_ENRICH_TOP_N',
    'architecture': 'NBD_MODE PFAM_ENRICH_BG NBD_CONF_EV_HIGH NBD_CONF_COV_HIGH NBD_CONF_EV_MED NBD_CONF_COV_MED ENABLE_REPEATLIKE_SENSOR REPEATLIKE_GROUPS_CSV TIER_REPEATLIKE_UNKNOWN_SENSOR',
    'asm': 'ASM_ENABLE ASM_WINDOW_NTERM_AA ASM_WINDOW_NBD_FLANK_AA ASM_MAX_EVALUE ASM_MIN_BITSCORE ASM_MIN_ALI_LEN ASM_ALLOW_MULTIHIT ASM_LOW_COMPLEXITY_MASK ASM_COUNTS_AS_SENSOR',
    'context': 'NLR_PROFILE HARD_END_BP SUBTELO_BP VERY_SHORT_PROTEIN_AA SHORT_PROTEIN_AA HIC_IDENTITY_THRESHOLD REPEAT_COLLAPSE_SCORE_BONUS',
    'rescue': 'SKIP_RESCUE_FOR_TIER1A INCLUDE_TIER3_IN_RESCUE REQUIRE_NBD_OK_IN_RESCUE_FASTA RESCUE_FILTER_LOW_NBD MINIPROT_EXTRA EXON_MAX_INTRON_RETRY',
    'fusion': 'ENABLE_FUSION MAX_FUSION_GAP_ILLUMINA MAX_FUSION_GAP_HIFI FUSION_GAP_BOOST_HARD_END FUSION_GAP_BOOST_REPEAT FUSION_MIN_NBD_CONF FUSION_MAX_OVERLAP FUSION_MAX_MEMBERS FUSION_EXCLUDE_FLAGS FUSION_NAMESPACE_MODE FUSION_PRIORITY_PREFIX FUSION_COMPREHENSIVE_PREFIX FUSION_ID_PAD_WIDTH',
    'reporting': 'REPORT_PLOT_BACKEND REPORT_PLOTS REPORT_INTEGRATION REPORT_TAGGED_GFF3 REPORT_TAGGED_EGGNOG REPORT_PROTEINS',
}
PARAMETERS = {key:(section,key.lower()) for section,keys in GROUPS.items() for key in keys.split()}
PARAMETERS.update({'NLR_PROFILE':('context','profile'), 'RESCUE_FILTER_LOW_NBD':('rescue','filter_low_nbd'),
    'ENABLE_FUSION':('fusion','enabled'), 'MAX_FUSION_GAP_ILLUMINA':('fusion','max_gap_illumina'),
    'MAX_FUSION_GAP_HIFI':('fusion','max_gap_hifi')})
for key in GROUPS['fusion'].split():
    if key.startswith('FUSION_'): PARAMETERS[key]=('fusion',key.removeprefix('FUSION_').lower())
PARAMETERS.update({key:('reporting',name) for key,name in [('REPORT_PLOT_BACKEND','plot_backend'),('REPORT_PLOTS','plots'),('REPORT_INTEGRATION','integration'),('REPORT_TAGGED_GFF3','write_tagged_gff3'),('REPORT_TAGGED_EGGNOG','write_tagged_eggnog'),('REPORT_PROTEINS','write_proteins')]})
FLAGS = set('PFAM_NBD_SCAN INCLUDE_DESC_KEYWORDS_IN_UNION DESC_KEYWORD_REQUIRE_STRUCTURAL_HINT UNION_INTERSECT_WITH_PROTEOME_IDS USE_PFAM_ENRICHMENT_FOR_UNION ASM_ENABLE ASM_ALLOW_MULTIHIT ASM_LOW_COMPLEXITY_MASK ASM_COUNTS_AS_SENSOR ENABLE_REPEATLIKE_SENSOR SKIP_RESCUE_FOR_TIER1A INCLUDE_TIER3_IN_RESCUE REQUIRE_NBD_OK_IN_RESCUE_FASTA RESCUE_FILTER_LOW_NBD ENABLE_FUSION REPORT_PLOTS REPORT_INTEGRATION REPORT_TAGGED_GFF3 REPORT_TAGGED_EGGNOG REPORT_PROTEINS INCLUDE_TIER3'.split())
ENUMS = {'REPORT_PLOT_BACKEND': {'matplotlib', 'r'}, 'NLR_PROFILE':{'ILLUMINA','HIFI'},'DISCOVERY_MODE':{'STRICT','BALANCED','BROAD'},'DESC_KEYWORD_STRUCTURAL_HINT_MODE':{'ANY','ALL'},'NBD_MODE':{'strict','relaxed','legacy'},'PFAM_ENRICH_BG':{'candidates','proteome'},'FUSION_MIN_NBD_CONF':{'HIGH','MEDIUM','LOW'},'FUSION_NAMESPACE_MODE':{'TRACK'}}
STRINGS = set(ENUMS) | {'DESC_KEYWORD_STRUCTURAL_HINT_SOURCES','REPEATLIKE_GROUPS_CSV','TIER_REPEATLIKE_UNKNOWN_SENSOR','MINIPROT_EXTRA','FUSION_EXCLUDE_FLAGS','FUSION_PRIORITY_PREFIX','FUSION_COMPREHENSIVE_PREFIX'}
NUMERIC = {'PFAM_ENRICH_MIN_LOG2FC','NBD_CONF_COV_HIGH','NBD_CONF_COV_MED','ASM_MIN_BITSCORE'}
EVALUE = {'EVAL_NBD','EVAL_PFAM','MAX_DOM_I_EVAL','EVAL_NBD_RELAXED','NBD_CONF_EV_HIGH','NBD_CONF_EV_MED','ASM_MAX_EVALUE'}
HIFI = {'EVAL_PFAM':'5e-4','MIN_DOM_ALI_LEN':25,'HARD_END_BP':1000,'CONTIG_END_BP':1000,'SUBTELO_BP':50000,'REPEAT_PROX_BP':50000,'EXON_MAX_INTRON_RETRY':10000,'NBD_CONF_EV_HIGH':'1e-8','NBD_CONF_COV_HIGH':0.50,'NBD_CONF_EV_MED':'1e-5','NBD_CONF_COV_MED':0.30}
DISCOVERY_PRESETS = {'STRICT':{'PFAM_ENRICH_MIN_LOG2FC':1.5},'BALANCED':{},'BROAD':{'INCLUDE_DESC_KEYWORDS_IN_UNION':1,'DESC_KEYWORD_REQUIRE_STRUCTURAL_HINT':0,'PFAM_ENRICH_MIN_LOG2FC':0.5}}

# These compatibility variables have no implemented scientific effect.
# Retain their defaults for provenance; reject changes that cannot take effect.
UNUSED_LEGACY = set("ASM_WINDOW_NBD_FLANK_AA ASM_ALLOW_MULTIHIT ASM_LOW_COMPLEXITY_MASK ASM_COUNTS_AS_SENSOR ENABLE_REPEATLIKE_SENSOR REPEATLIKE_GROUPS_CSV TIER_REPEATLIKE_UNKNOWN_SENSOR HIC_IDENTITY_THRESHOLD REPEAT_COLLAPSE_SCORE_BONUS".split())
